console.log("first")
console.log("second")
try{
consol.log("third")
}
catch(err){
    console.log("err is ",err)
}
console.log("fourth")

function test(){
    console.log("test called")
}

test()

